test:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*_test.go"
      - "**/testdata/**"
      - "**/test/**"

documentation:
  - changed-files:
    - any-glob-to-any-file: ["**/*.md", "**/*.txt"]
