run:
  timeout: "10m"
  issue-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  allow-parallel-runners: false
  go: "1.20"

linters-settings:
  misspell:
    locale: "US"
  govet:
    enable-all: true
    check-shadowing: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - forcetypeassert
    - gocritic
    - goimports
    - gosimple
    - govet
    - makezero
    - misspell
    - nilerr
    - noctx
    - revive
    - staticcheck
    - unused

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
