name: lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
