name: govulncheck
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@v1.0.3

      - name: Run govulncheck
        run: govulncheck ./...
        working-directory: ${{ github.workspace }}
